version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
  
  test:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - run: npm i

  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: npm i
          
workflows:
  my-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
